name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILDHOOK }}